#!/usr/bin/env python3

import sys


def typer():
    codepoints = []
    print('Enter Tibetan Unicode points:', file=sys.stderr)

    try:
        while True:
            codepoints.append(int(input().strip(), base=16))
    except KeyboardInterrupt:
        pass

    print(''.join(chr(c + 0x0f00) for c in codepoints))


if __name__ == '__main__':
    typer()
