

def graph():
    return {
        'k': {
            'w': True,
            'y': True,
            'r': True,
            'l': True,
            's': True,
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'kh': {
            'w': True,
            'y': True,
            'r': True,
            'l': True,
            's': True,
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
            # 'zh',
            # 'z',
            # '\'',
            # 'sh',
        },
        'g': {
            'k': False,
            'kh': False,
            'c': False,
            'ch': False,
            'j': False,
            'ny': False,
            't': False,
            'th': False,
            'd': False,
            'n': False,
            'p': False,
            'ph': False,
            'b': False,
            'm': False,
            'ts': False,
            'tsh': False,
            'dz': False,
            'w': False,
            'zh': False,
            'z': False,
            '\'': False,
            'y': True,
            'r': False,
            'l': False,
            'sh': False,
            's': False,
            'h': False,
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'g.': {
            'k': False,
            'kh': False,
            'c': False,
            'ch': False,
            'j': False,
            'ny': False,
            't': False,
            'th': False,
            'd': False,
            'n': False,
            'p': False,
            'ph': False,
            'b': False,
            'm': False,
            'ts': False,
            'tsh': False,
            'dz': False,
            'w': False,
            'zh': False,
            'z': False,
            '\'': False,
            'y': False,
            'r': False,
            'l': False,
            'sh': False,
            's': False,
            'h': False,
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'ng': {
            'k',
            'kh',
            'g',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'c': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'ch': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'j': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'ny': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        't': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'th': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'd': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'n': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'p': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'ph': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'b': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'm': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'ts': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'tsh': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'dz': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'w': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'zh': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'z': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        '\'': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'y': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'r': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'l': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'sh': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        's': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'h': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a': False,
            'i': False,
            'u': False,
            'e': False,
            'o': False
        },
        'a': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a'
        },
        'i': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a'
        },
        'u': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a'
        },
        'e': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a'
        },
        'o': {
            'k',
            'kh',
            'g',
            'ng',
            'c',
            'ch',
            'j',
            'ny',
            't',
            'th',
            'd',
            'n',
            'p',
            'ph',
            'b',
            'm',
            'ts',
            'tsh',
            'dz',
            'w',
            'zh',
            'z',
            '\'',
            'y',
            'r',
            'l',
            'sh',
            's',
            'h',
            'a'
        }
    }
